packages:
    - apps/*
    - libs/*
    - packages/*

catalogs:
    tooling:
        "@moonrepo/cli": "~2.3.5"
        "prettier": "~3.9.4"
        "prettier-plugin-organize-imports": "~4.3.0"

savePrefix: "~"

minimumReleaseAge: 4320
trustPolicy: no-downgrade
engineStrict: true
