name: craftsmans-ledger
services:
    admin-portal:
        image: ghcr.io/nonamer777/craftsmans-ledger/cml-admin-portal
        container_name: admin-portal
        restart: unless-stopped
        ports:
            - '7100:80'
        volumes:
            - ./config.json:/usr/share/nginx/html/config.json
