name: craftsmans-ledger
services:
    web-app:
        image: ghcr.io/nonamer777/craftsmans-ledger/cml-web-app
        container_name: web-app
        restart: unless-stopped
        ports:
            - '7000:80'
        volumes:
            - ./config.json:/usr/share/nginx/html/config.json
