name: Setup Tools
description: Sets up Node.Js
runs:
    using: Composite
    steps:
        - name: Setup Node.Js
          uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
          with:
              node-version-file: '.tool-versions'
              cache: 'npm'
              cache-dependency-path: './package-lock.json'

        - name: Install dependencies
          shell: bash
          run: npm ci

        - name: Set main branch ref
          if: github.ref != 'refs/heads/main'
          shell: bash
          run: git rev-parse --verify main || git remote set-branches origin main && git fetch --depth 1 origin main && git branch main origin/main
