name: Setup Tools
description: Sets up Node.Js
runs:
    using: composite
    steps:
        - name: Setup Node.Js
          uses: actions/setup-node@v4
          with:
              node-version-file: '.tool-versions'
              cache: 'npm'
              cache-dependency-path: './package-lock.json'

        - name: Install dependencies
          shell: bash
          run: npm ci

        - name: Set main branch ref
          if: github.ref != 'refs/heads/main'
          shell: bash
          run: git rev-parse --verify main || git remote set-branches origin main && git fetch --depth 1 origin main && git branch main origin/main
