ktor:
  application:
    modules:
      - org.eu.nl.ApplicationKt.module
#  development: true
  deployment:
#    host: localhost.api.craftsmans-ledger.net
    port: 7200
#    sslPort: 7200
#  security:
#    ssl:
#      keyAlias: craftsmans-ledger-key
#      keyStore: keystore.p12
#      keyStorePassword: ${KEYSTORE_PASSWORD}
#      privateKeyPassword: ${KEYSTORE_PASSWORD}
