name: CI
on:
    push:
        branches:
            - master
    pull_request:
permissions:
    contents: read
env:
    MODE: ${{ vars.MODE }}
jobs:
    ci:
        name: CI
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Setup Tools
              uses: ./.github/actions/setup-tools

            - name: Check linting
              run: npx nx affected -t lint --verbose

            - name: Check formatting
              run: npx nx format:check

            - name: Compile code
              run: npx nx affected -t build
