name: craftsmans-ledger
services:
    admin-portal:
        image: craftsmans-ledger/api
        container_name: api
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - '7200:7200'
